### ISSUE TITLE
File paths should be relative to parent object/file

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#101]
The paths in `app-config.json` and map configuration files should by default be relative to the originating file.  For example, paths in `app-config.json` should be relative to itself.  We are making a design decision that `/assets/app` is the default application root.  All file references will be relative to that.  Therefore, a map file should be specified as `map-configurations/mymap.json` and the full path for internal code would be:

`/assets/app/map-configurations/mymap.json`

Similarly, when a map configuration file references a layer file,  the full path to the layer file would be the folder of the map configuration file (`/assets/app/map-configurations/`) appended with the source path of the layer (e.g., `../map-layers/mylayer.geojson`).

**The only thing hard-coded is the top-level `/assets/app`.**  However, creators of maps would never have to specify this since everything is relative to the application and map configuration files.

See [Java toAbsolutePath and toRelativePath code](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/Util/IO/IOUtil.java).  This code discards extra `..` to make paths look nice.  The Angular code can hopefully be cleaner because it is not dealing with drive letters or backslashes.

**Comment by smalers** [comment]
This seems better but I'm getting errors displaying a map.  See the attached image.  It seems like some of the path variables are getting mixed up.  The transbasin (which is the last map in Entities menu) is somehow trying to be used even through I clicked on "Administrative Water Districts".

![image](https://user-images.githubusercontent.com/6448274/81895639-f4408900-956f-11ea-881f-16d10956a42c.png)

**Comment by Nightsphere** [comment]
I pushed a couple hours dealing with this issue, but I'm not closing the issue yet until I'm convinced it's taken care of

**Comment by Nightsphere** [comment]
There have been quite a few map config files used, and problems with the relative paths have not
shown themselves. I will close this issue.
