### ISSUE TITLE
File mode (permissions) are wrong on many files

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#102]
When I pulled, many files are indicated as having mode change from 644 to 755, the latter being for executable files.  I suspect that Josh is mixing Cygwin and Git Bash environments.  Once you clone with an environment, you must stick with it.  Otherwise permissions get screwed up.

This is why I created the `z-local-notes` folder.  I put a file there to tell myself what environment I used so that I stay with it.  DO NOT edit the `README.md` in that folder.  Create a different file.  If things are too messed up,  he might need to clone again and then set the permissions correctly.  

It should also be obvious when something is wrong when many files are marked for a commit. 
 Search for files that are executable with:

```
find . -executable -type f
```

Pipe the above to `grep -v` to filter out noise.

**Comment by Nightsphere** [comment]
Permissions have been updated and a file in the z-local-notes has been created for the local
environment used so this does not happen again. Closing the issue.
