### ISSUE TITLE
Extent properties do not match the specification.

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#105]
The extent should be specified as follows:

```
"extentInitial" : "ZoomLevel:-105.385,40,8"
```

In other words, the ZoomLevel encoding is part of the data value, not the property name.  This allows flexibility to have variations on property names `extentMaximum` and also support multiple encodings without adding additional properties.  The code that parses the extent can also be generic for any extent property.  See the GeoMapProject specification for full description.

**Comment by Nightsphere** [comment]
I just pushed with the update for extentInitial property. The command files in the repo should be
correct, and a map configuration file with the ZoomLevel should be good to go now.

**Comment by smalers** [comment]
This is working now.  I'm closing the issue.
