### ISSUE TITLE
Category classification file needs to allow # comments.

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#106]
The classification file needs to allow `#` comments.  This allows the contents of the file to be described.  Comment lines are needed at the top, and ideally can also be used anywhere in the file to comment out a specific line.  Papaparse should allow this.

**Comment by Nightsphere** [comment]
I have made a push for this. It should be working now, but I'll wait to close the issue.

**Comment by smalers** [comment]
I tested this and it works.  Will need to support the same functionality for other similar tables.  I'm closing this issue.
