### ISSUE TITLE
Improve error handling of extentInitial

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#112]
Hopefully this is easy.  I used `ExtentInitial` instead of `extentInitial` and the map would not load and an exception was shown in the console related to "split".   There should be more graceful handling of such things.  For example, the initial extent is not critical and should worst case default to the world view, or if more sophisticated, default to the maximum extent of all the layers.

More generally, bad configuration data should ideally allow the map to be drawn, but maybe not be drawn as expected.  The console message should say something like `Unknown property xxxx`, or `Missing property xxx - defaulting to abc` (although I'm not sure this should be shown in normal run mode), or `Property xxx value (abc) is badly formatted.`, similar to TSTool command editor warnings for bad input.  These messages should provide enough information to quickly track down the issue, so include the GeoMapProject, GeoMap, etc. identifiers in message.  The message may be verbose but will save a bunch of time.

Perhaps we need a property in the map configuration file `debug : true` to turn on more extensive messages.  If false (the default) console messages will only be for critical output.  If debug=true, then more messages will be output.  If there is not already some type of logging, methods could be created for `debug`, `warning`, etc. similar to other languages, for example in a `Logging` class.  We can discuss this.

I found this [Logging in Angular Applications](https://www.codemag.com/Article/1711021/Logging-in-Angular-Applications) article.  It would be good to talk to Catherine.

**Comment by Nightsphere** [comment]
The `extentInitial` error handling has been updated and is now more verbose to help with troubleshooting. I will keep the logging service in mind for the future. Closing the issue.
