### ISSUE TITLE
Comment out the autopan tools if possible

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#115]
Apparently we don't know what the autopan tools do.  Maybe it recenters the map on visible layers?  For now, comment out that code so the tool icon is not visible.  The code can be enabled again if we figure out what the tool does and it meets a need.

**Comment by Nightsphere** [comment]
The autopan has been commented out and can be easily brought back in if we need to in the future.

**Comment by Nightsphere** [comment]
Until we decide to bring autopan back, I'll close the issue for now.
