### ISSUE TITLE
Add tool to zoom to initial extent

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#116]
Need a tool to zoom to the map initial extent, to be used when the user has zoomed and panned and wants to get back to the starting point.   An icon can be added to the tool tray on the left.  See the QGIS "Zoom full" icon.

**This is low priority but I'm putting on the backlog.**

**Comment by Nightsphere** [comment]
As of now, there is a 'home' button in the upper right part of the map, in-between the plus and minus
signs that will bring the map view back to the initial extent as specified by the user for the ZoomLevel

**Comment by smalers** [comment]
Keep this open until I have a chance to document the feature for users.

**Comment by smalers** [comment]
The documentation has been updated.  Close the issue.
