### ISSUE TITLE
classification property should be classificationType

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#117]
In creating additional maps, I found the following problem.  The `classification` property should be `classificationType` as per the specification, for example:

```
"classificationType" : "Categorized"
```

The check of the value can ignore case.

**Comment by Nightsphere** [comment]
It seems this property was a leftover from when Justin was working on the poudre dashboard. All
subsequent map configuration files won't have this property and instead will use the
classificationType property instead

**Comment by smalers** [comment]
This issue is fixed.  I changed my map configurations to `classificationType` and the maps work.  Close the issue.
