### ISSUE TITLE
Legend area is not displaying correctly

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#119]
The legend area is not displaying properly given recent changes.  It is good that some of the controls have been removed - and they can be added again with smaller footprint.

To be clear, here is what should happen:

1. The `geoLayerViewGroups` array in the JSON will list layer view goups from top to bottom, meaning that the group listed first will show on the top of the map (and in the legend).  Conversely, the group listed last will be drawn first.
2. Similarly, the `geoLayerViews` array in the JSON will list layer views from top to bottom, meaning that the layer view listed first will be shown on the top of the map (and in the legend).  Conversely, the  layer view listed last will be drawn first.

This ensures that someone that is reviewing the map configuration file sees array order that matches the map legend and the order of layers on the map.  It puts burden on drawing code to process the arrays in reverse order, but that should be straightforward.

I will make sure the GeoMapProject documentation matches this.

**Comment by smalers** [comment]
**Important** the processing order is really important.  It won't be obvious if only one layer view is in a layer view group, so we need tests and examples that have 2 or more layer views in a layer view group, etc.  If there is typically a background layer and another group, then there should always be at least 2 layer view groups.

**Comment by smalers** [comment]
The order of the layers on the main map does not seem correct.  The base layers are clearly on the bottom.  However even though the map configuration file has geolayerviews in order stream gages, diversions, and then reaches, the lines of the reaches are drawn on top of the point symbols.  This makes the map more difficult to read, and the mouse-over does not work as well because you have to avoid the river lines.

The order of views in the map configuration file should control, legend being in the order of the view list, and drawing being in the reverse order.  **The legend seems to be OK, so don't break that, but the order drawing the map may not be correct. **

**Comment by Nightsphere** [comment]
The layer order should be correct from now on, but I'm still working on the ability to display different viewGroups

**Comment by Nightsphere** [comment]
The legend area is now (finally) displaying correctly. I will push before the next 2 hours, but want to make sure theyre aren't
any large issues or minor ones that would stand out visually. This issue won't be closed until more rigorous testing with
more complicated geoMapProject configuration files have been used.

**Comment by Nightsphere** [comment]
A new push was just added with what I hope is the full, robust solution to keeping layer order preservation. This should take
care of initial ordering and toggling of layers on and off. Not closing until more rigorous testing with many map layers is tested.

**Comment by Nightsphere** [comment]
This has been working correctly since I've gotten rid of the dynamically created components and just displayed each layerView conditionally. We can reopen if problems persist in the future. Closing the issue.
