### ISSUE TITLE
Navbar enhanced display

### ISSUE THREAD

**Issue by jurentie** [OpenWaterFoundation/owf-app-info-mapper-ng#12]
I've added dropdown menus with examples of two different kinds of icons. A map icon next to links that will open a map and an external link icon next to other dropdown options. I think it would be good to add some sort of "active" style to selected items. I am currently struggling with typescript to add this to the project, but it shouldn't be too difficult once the typescript hurdles are figured out.

**Comment by Nightsphere** [comment]
I think the menus are in a good place for now. If other enhancements need to be implemented
later I can open up new issues. Closing this issue.
