### ISSUE TITLE
Clarify warning for classsificationAttribute

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#120]
I added a new layer to an existing map and got the following warning:

```
The classification file property 'classificationAttribute' is incorrect. Double check the feature property needed for classification
```

The message could be improved to something like:

```
The classification file property 'classificationAttribute' value 'DIVISION' was not found. Confirm that the specified attribute exists in the layer attribute table.
```

**Comment by Nightsphere** [comment]
The warning has been improved to be more informative if a classificationAttribute is incorrect. I will
also keep this in mind for other properties in the config files given. Closing the issue.
