### ISSUE TITLE
Autodetect URLs in default popup and enable link

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#124]
For the default popup, need to auto-detect URLs and enable a link in a separate tab.  Check for attribute value that is a string starting with `http://` or `https://`, which will be used for most URLs.  This default will help with many layers.

**Comment by Nightsphere** [comment]
I have implemented this, and URL's should now be detected and will open in a new tab. Closing
this issue.
