### ISSUE TITLE
Popup title should be the layer corresponding to popup data

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#129]
The popup that shows layer attributes is currently labeled with the map name.  This is confusing because when there are multiple layers, especially overlapping layers, you don't know what layer the data is for.  I suggest:

1. Show the GeoLayerView name as the title in the popup (same as what is shown in the legend).
2. Change the left panel ***Tools*** to the GeoMap name.

That above should improve the user experience.

**Comment by Nightsphere** [comment]
The categorized polygon will display the geoLayerView name in the popup title, but not the others. They still need to be worked on.

**Comment by Nightsphere** [comment]
All map popups will now start off by showing the map name by default, and then update to the
geoLayerView name once a mouseover is detected. Closing this issue.
