### ISSUE TITLE
Mouseover popup layer is latest selected layer

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#130]
**This item may take some effort to sort out.  It is high priority but there are workarounds and therefore other smaller high priority items and critical items should be addressed first.**

Maps with multiple layers can behave in unpredictable ways when displaying and providing mouseover information.  For example, the Poudre application ***Basin Entities / Administration - Division 1 Water Districts*** map seems to draw the map layers in the correct order and are listed in the legend correctly.  However, the mouseover shows data for the latest selected layer.  When initially drawn, the division boundary is somehow selected and mouseover shows data for it.  However, if the water districts layer is turned off an then on, it becomes active and the mouseover popup displays data for it.  See the following (which may change as it is updated):

[Poudre Basin Information](http://poudre.openwaterfoundation.org/0.2.0.dev/)

In QGIS ***Layers*** list, there is a checkbox to the left of each layer, indicating what should be drawn.  There is also a way to highlight the layer, and `Ctrl` and `Shift` can be used to select more than one layer.  These are shown with darker background for the row.  The latter controls what information the ***Identify Features*** tool will use.  However, selecting more than one  layer seems to confuse this tool.

In Leaflet, a point layer drawn on top always seems to allow mouseover to show its data.  However, overlapping polygon layers only show mouseover for the latest selected layer.  I recommend that we do the following:

1. Try to document this in the InfoMapper user documentation so users know what is going on.
2. Find a way to indicate which GeoLayerView is selected for an action.  Maybe show the info icon with a checkbox on top of it?  If selected, the icon would have a darker (selected) look and if not selected the icon would have a lighter (not selected look?  I can see how the layer view could be selected for things other than info, so I'm not sure an info-focused icon is the best.  Maybe change the geolayer view name display to bold or something else visual?
3. Add a tool on the left edge of the left-side panel.  For example, use an ***Identify Features*** icon similar to QGIS.  This would turn the mouse-popup on-off.   Because default of on is nice, this is a lower priority.   An icon could be shown in selected mode (dark background) and leave on as the default for now.  The second item above is more important.
4. Need to run a test where we have polygon layers that overlap in some part of the map and don't overlap in other part of the map to see how Leaflet performs.

At a minimum, we need to make the behavior more predictable and understandable.

**Comment by smalers** [comment]
I found [this article](https://stackoverflow.com/questions/16827147/layer-order-changing-when-turning-layer-on-off/24815243).  Not sure if it is useful.

**Comment by Nightsphere** [comment]
Now that the layerOrder function is called after a user turns a layer off or on, as well as being called when the map is created,
we no longer need to worry about the mouseover displaying the most recently selected. The layers should (pending more
testing) be in the correct order at all times. I'll keep this open for now since it has some other good ideas like letting the user
know in the side panel what layer is currently being used or selected.

**Comment by Nightsphere** [comment]
This issue has not presented itself in a while now, and I think has been taken care of. We can open again if it crops up sometime in the future. Closing the issue.
