### ISSUE TITLE
Need map information content 

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#131]
Each map needs the option to provide content describing the map.  This goes far beyond the 1-3 sentence description.  It would be implemented with a new property such as `aboutDoc`, which would specify the path to a Markdown file.  The file would be converted to HTML and displayed somewhere, possibly a well-behaved popup.  The document might be complex, with images, links, etc.  Therefore, a standard folder would need to be determined, for example parallel to `layers`.

To access the documentation, perhaps have an image/button in the tool area on the left, which would be enabled if the map had a content file, otherwise, disable the tool.

This feature will be needed where it is not obvious what the map is showing and if trying to be transparent about explaining how the map was created.

**Comment by smalers** [comment]
Maybe it would be best to use a property `docPath` that would be allowed as a map property, GeoLayerViewGroup property, and GeoLayerView property.  The path would follow normal rules for relative/absolute.  Given that documentation is easier to deal with, the file extension could indicate whether the documentation is markdown (`.md`),  `.html`, or `.txt`.  If the property is found, it would result in an "info" icon begin shown at the appropriate level.  Then when the user clicks on the icon, they will see a popup (modal?) that shows the documentation.  Or, display in another tab as full HTML.  This is somewhat related to other tasks that deal with displaying documentation.  The actual location of the documentation would likely be at the level of the object, such as map or layer.  Maybe we need another property to indicate the identifier shown in the URL?  I can see how the name of the file might not be unique so we might need the identifier.

The documentation could have a link to the OWF repo that describes the workflow and could have other links.  One thing we may do is add a metadata file for layers, using standard GIS metadata file formats.  These are a bit of a pain to deal with but I'd like to automate if possible.

**Comment by Nightsphere** [comment]
The `docPath` property has been added in the new merge. This has only been done for a geoLayerView for right now, so if the
property exists in a geoMap or geoLayerViewGroup, nothing will happen right now. I will work on implementing that
tomorrow. If the `docPath` property exists in the geoLayerView, an info icon will appear to the left of the layer toggle button in
the legend. 

`.md` and `.txt` files have been implemented, but I need to do a little bit more work on straight html files. I should also have
these working by tomorrow as well.

**Comment by smalers** [comment]
The new feature is a good start.  The `docPath` is interpreted relative to the GeoMapProject file, similar to layers, which makes sense.  I created a markdown file with the same name as the layer, but extension `.md`.  I have the following feedback:

1. The info buttons would benefit from general tooltip such as `Click to view layer documentation, Ctrl-click to view in a new tab` (assuming that the Ctrl-click can get worked out.  Similarly `Click to view layer group documentation` and `Click to view map documentation`.
2. As discussed, the big issue is that the links need to behave well, for example:
   1. If displayed in a popup, the popup should handle links internal to the popup, such as a fully-functional iframe.
   2. If displayed in a tab, the browser should hopefully handle as if a normal web page.
   3. **Do not** let an external link replace the application itself because that results in a lot of disruption in user experience.
3. The documentation could have levels of complexity that hopefully can be supported, but start with simple level.  In cases where multiple files are used, I will probably put in a folder to isolate documentation files from other files.
  1. Just text, no links.
  2. Text with images.
  3. Text, images, and links within same page.
  4. Text, images, and links to external pages

**Comment by Nightsphere** [comment]
Another push has been added with Angular tooltips on all buttons in the side bar. If any small wording changes needs to
happen, it will be simple to update.

**Comment by Nightsphere** [comment]
The core map documentation has been added. Anything else can be opened as a separate issue. Closing this issue.
