### ISSUE TITLE
Background layers hamburger menu labels are wrong

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#132]
The hamburger menu for background layers is showing the layer ID.  Instead, it should be showing the name so that the labels match the legend.   The IDs are for internal use and are ugly.

![image](https://user-images.githubusercontent.com/6448274/82949995-cdb42200-9f61-11ea-978d-0127d1f2c876.png)

**Comment by Nightsphere** [comment]
I looked at the code and it was also going through the geoLayers instead of the geoLayerViews. I updated, and it should now display the correct name for each of them. I will close this issue.
