### ISSUE TITLE
Need TypeScript code to read common time series file formats

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#138]
Now that the InfoMapper is displaying time series, we need more flexibility to read time series data file formats other than csv.  This will ensure that data files that are already in use for State of Colorado projects and other systems can be read as is.  These formats also may provide more metadata about the time series, whereas csv are limited (unless we figure out how to provide metadata in comments or a secondary file).  Multiple formats may be loaded to a static website, for example to allow use in software and download by users.  The following is Java code that needs to be ported to TypeScript.  The focus right now is month and year interval, but other intervals will be needed in the future.

* [StateMod_TS](https://github.com/OpenCDSS/cdss-lib-models-java/blob/master/src/DWR/StateMod/StateMod_TS.java) - need this ASAP to support State of Colorado StateMod dataset visualization project, focusing on monthly interval
* [DateValueTS](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/TS/DateValueTS.java) - this is a good general purpose format that TSTool uses and could be used if csv is not sufficient
* JSON - there is a general JSON format; however, nobody uses in modeling, etc. so hold off on this

In the above, the main focus should be the read functionality given that InfoMapper will read the time series and display.  Any features to download data will probably be links to pre-existing files.

The above code depends on other classes, such as the generic [TS](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/TS/TS.java) for time series.  It should be possible to port this code to TypeScript, commenting out features that are not urgently needed.  Taking short-cuts on this may be more trouble than it is worth so porting multiple supporting classes probably makes sense and will support long-range features of the tool.  Note that the design of TS could be improved, for example by using more interfaces.  However, the fundamental design is sound.  **Consult with me if there are questions about how deep to go on the porting.**

**Comment by Nightsphere** [comment]
The push for this has been made. I won't close this issue until we've done more testing.

**Comment by Nightsphere** [comment]
Overall, the main purpose of this issue is complete. Both StateMod and DateValue have been implemented and can be read and displayed in either Chart.js or Plotly, with multiple graphs on each with differing chart types. If smaller updates need to be done, more issues can be opened later on. (Implementing IrregularTS, MinuteTS, etc..) Closing the issue.
