### ISSUE TITLE
Don't show popup when mouse is not over a feature

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#139]
Now that the mouseover popup correctly shows the layer for the feature that is moused over, there is a different issue.  The popup can be large (hopefully we'll fix that with template) and can obscure a large part of the map.  The popup remains even if not moused over a feature.  It can also be confusing because maybe the person is mousing over something else and their aim is off...and it continues to show the old information.

It would be good if the popup goes away when not moused over a feature.  Then the map would not be obscured.  This may be something that we try and then go back to the current behavior.  I recommend making the code allow either behavior via a variable and then we can default to what we decide is best.

**Comment by Nightsphere** [comment]
This has been pushed and is taken care of for now. If we change our minds we can reopen this issue
or reassign it later.
