### ISSUE TITLE
Allow home content page to be configable

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#140]
For some reason the home page for a new application is not showing the home page.  The URL flashes as `content-page/home` but then goes to the `map-error` page.

It seems like the home page is assumed to be in a certain folder.  Can the path to the home page be configurable, for example as `homePage` main configuration property?   It would be something like:

```
"homePage" : "/contentPages/home.md"
```

Or should we use `indexPage` and `errorPage` so we can follow typical web conventions?

I'm going to add some maps (all are currently undefined ).  Maybe that will make the home page show up.  I'm adding this issue because the home page seems like one of the few things that is still hard-coded.  Also, maybe issue #51 can be closed?

**Comment by Nightsphere** [comment]
I pushed new changes that will have the home page be configurable. I added the `"homePage"`
property in the app config, with a leading `/` like in your example above. Now the path to the home
page can be given, along with the extension. There is also error handling letting the user know if the
property isn't set at all, or if the path is incorrect. I will close this issue.
