### ISSUE TITLE
Need way to start new tab for external links in content pages

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#142]
**Maybe this is a task that Sofia could work on since she worked on Markdown/slowdown.**

The content pages often contain links to external pages.  However, if the link is followed on the same web page, the InfoMapper goes out of scope.  Using the browser back button then causes the InfoMapper to totally reload (unless something is cached).  Therefore, it would be good to have the ability to format Markdown in a way that results in links opening in new tabs.  This is a bit irritating, but hammering the application for every external link is another kind of irritation.   If the solution cannot be implemented using an elegant addition to Markdown, then I need to know if anyone has ideas.

There may also be a need to granularly control whether a link opens a tab, window, or needs to be handled in the application routing.

**Comment by smalers** [comment]
Maybe there should be some properties at the same level as `markdownFile` such as `openLinksInNewTab`?  We don't want the main application configuration to get too ugly, but a few additional properties might cover a lot of the bases.  We could even make this behavior the default and allow turning off if someone really wants it.  The ability to control at a granular level with CSS would still be good to figure out also.

**Comment by Nightsphere** [comment]
Sofia was able to find a showdown option that enables all external links to be opened in a new tab. We should have no problems with this anymore. Closing this issue.
