### ISSUE TITLE
Zoom increment with mouse wheel is too large

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#145]
The initial zoom extent for maps is typically configured OK, although I'm not sure how well it works for different display sizes.

However, trying to change the zoom level with the mouse and zoom tool often jumps the zoom level too much, resulting in a map that is either too small or too large.  I'm assuming that the current software is jumping the zoom level by whole integers.  However, jumping by .1 or .25 or some other reasonable increment would likely result in a better user experiences.  So, I'm suggesting changing the default increment.  If it works well, then the default can stick.

I could see that if we are building tools that range from small basins to the entire US that the default increment of the zoom level might need to change, but seems like an advanced topic.  Maybe shift or ctrl key could be used to indicate when to "accelerate" the zoom and have the default be appropriate for a typical state-sized map.

**Comment by smalers** [comment]
Also, need to be able to set the extent to fractional zoom.  I recommend setting the zoom snap for Leaflet to .1.

**Comment by Nightsphere** [comment]
There is a new push with some changes to the zoom. For one, I changed the mouse wheel scroll to
zoom in and out and the absolute slowest interval possible, but it wasn't as big of a change as I
thought it would be. Steve will have to let me know if he can tell the difference. I also changed the 
`zoomSnap` to 0.1, but again couldn't really see much change.

**Comment by smalers** [comment]
The zoom level for initial extent and mouse seem to be working well.  Close this issue.
