### ISSUE TITLE
Point single symbol properties not working

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#147]
I tried to change the properties for single symbol for a point.  The application did not display the layer.  The following was what I ultimately had to use:

```
symbolShape:Diamond,color:cyan,fillColor:cyan,size:6,sizeUnits:pixels,opacity:1.0,fillOpacity:1.0,weight:1.5
```

I was hoping to specify only `symbolShape` and `color` and have the others default.

I had similar issue setting single symbol property for line layer, where I wanted to set only `color`.

The code needs to handle minimal properties and use defaults.  See the specification documentation for defaults.  If the specification needs to be updated, let me know.

**Comment by Nightsphere** [comment]
The new push is up and points & polygons will now have default values if none are given in the map
config file. Closing the issue.
