### ISSUE TITLE
Turning layer on and off changes the render order

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#150]
The initial rendering order on a map seems to be OK and matches the GeoMapProject order.  However, turning layers on and off via the legend panel causes the most recently manipulated layer to draw on top.  There needs to be some code that enforces the original map order.  Hopefully it happens quickly so the user does not notice any weird rendering visual glitches.  See also issue #133.

**Comment by Nightsphere** [comment]
Luckily, this was as easy as I thought it would be! When the layer is toggled off, the layer goes away.
When the layer is toggled back on, one line of code calls the resort layer function, and layer order is
preserved.

I have been staring at it when it happens and can't even tell it's doing the resorting, so to
the user it looks like when the layer is turned back on, it just gets drawn in the same order it was
before. Closing this issue.
