### ISSUE TITLE
Map project absolute path breaks the map when deployed

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#152]
Specifying the path to the map configuration using an absolute path, for example `/data-maps/some-map.json` works OK in the development environment but causes a `//` in the deployed system URL and does not work.  A slash in front of a path should be consistently handled for all file resources as per the specification:

* [`app-config.json`](http://software.openwaterfoundation.org/infomapper/latest/doc-user/appendix-install/app-config/#path-specification)

This seems to work well for other files such as images and content pages and it will hopefully also work for time series files located in `/data-ts`.

If it is necessary to go to the Angular assets root, we could add support for `//` at the front of paths, for example to reach `//app-default/` files.  Hopefully we can avoid that?

**Comment by Nightsphere** [comment]
A new push has been added that takes care of this, as well as time series file location paths. Double //'s should not be a problem anymore. Closing the issue.
