### ISSUE TITLE
Application locks up

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#153]
The [StateMod dataset application](http://opencdss.openwaterfoundation.org/datasets/colorado/2015/) has locked up a few times and shows either a black screen or black in areas where the window is resized larger.  Sometimes a "Wait?" dialog will be displayed.  It is not clear if it is due to large map layers being shown (which could be a problem for any application), or is it a logic problem?  The problem is that if it locks up, then the window is unresponsive and cannot be inspected.  Maybe there is something that could be monitored in the application code to see if a situation is manifesting.  Is there a "lint" tool or other Angular packages.

I also think that we are going to need to deal with caching maps sooner than later.  If a user switches between "static" maps, it should not be necessary to fully re-read data and reinitialize maps.   It should be possible to just swap in the map that was previously read.  I'm speaking generally without knowing the details of the code.  My main concern is that if the application is locking up, we need to figure that out and anything that can be done in the design to improve on performance and memory management could help.

**Comment by smalers** [comment]
I duplicated this when I used the following layer in Poudre municipal boundaries.

[CIM Municipal Boundaries](https://data.colorado.gov/resource/w6jq-7em5.geojson",OutputFile="downloads/municipal-boundaries.geojson)

The issue did not manifest itself in the development environment, only when deployed to the cloud. 
 I have a few ideas:

* Read and rewrote with GeoProcessor to trim number of digits in coordinates from 14 to 5.  This reduced the file size and also added newlines, which makes the file easier to edit, but the map still locked up.
* Maybe it is the shape type, but a little research did not turn anything up.
* Other polygon layers re bigger, so not sure if it is related to size.  It could be that a polygon has more vertices than a limit allows?

For now I commented out using the layer.

**Comment by Nightsphere** [comment]
I believe what was happening was the code was undependable and would sometimes get stuck in an infinite loop. The new code should fix this, and display the map layers in the correct order much faster
than what was used previously. This issue shouldn't be closed until more testing has been done on it.

**Comment by smalers** [comment]
I have not seen this behavior lately so I'm going to close the issue.  It seems that asynchronous tasks are being handled consistently.
