### ISSUE TITLE
homePage needs to accept relative path

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#154]
The new top-level `homePage`  property only accepts a path with leading slash, as in the following:

```
"homePage": "/content-pages/home.md",
```

It also needs to accept the equivalent, which is easy to try, but generates an error:

```
"homePage": "content-pages/home.md",
```

**Comment by Nightsphere** [comment]
This will now accept both absolute and relative paths for the home page. Closing the issue.
