### ISSUE TITLE
Popup can only be clicked once?

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#158]
It appears that popup can only be clicked once on each shape.  A user should be able to open a popup  for a feature as many times as they want.  See for example:

[Poudre Education Organizations](http://poudre.openwaterfoundation.org/latest/#/map/entities-education)

**Comment by Nightsphere** [comment]
I won't close this yet, but I have done a new push that has taken care of this issue. This should fix all
shapes, lines, polygons and images on the map. I'll keep testing it more as I work on other issues.

**Comment by Nightsphere** [comment]
After more testing, I will close this issue, and it can be opened again if we run into more trouble later on.
