### ISSUE TITLE
Text size for link in popups is too small

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#159]
The popup displays links in text size that is smaller than other text.  It appears that there is some generic logic to set the size.  The solution needs to ensure that the link text is reasonably readable and never gets really small.  I can see a few options to fix this:

1. Allow links to wrap within the popup dialog.  This might look ugly.
2. Set the text size based on a graduation of link length.  The smallest text still needs to be readable.
3. Truncate the visible link, for example by showing first and last parts and using `...` in the middle.
4. Allow the link text to be different from the link URL.  This would help if configurable template formats are configured.  The link name would typically be a short name.
5. Other ideas?

**Comment by Nightsphere** [comment]
The URL text will now wrap, and stay inside the popup. It will now just take up multiple lines instead. I have pushed the code for this and will close this issue.
