### ISSUE TITLE
Single symbol for line layer in legend is not displayed

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#162]
The singleSymbol classification type for line layers is not showing a layer in the legend.  Perhaps the line width needs to be wider?  See QGIS for one approach.  I have also seen a `/\/` shape used in legend, which might be easier to see.  Also, sometimes, when drawing, you need to issue a "stroke" or other command to cause the rendering to occur, which flushes the drawing buffer.

**Comment by Nightsphere** [comment]
I have added a debug statement that will hopefully solve this mystery of why it's working on my
local machine but not elsewhere. Also, the displaying of images in the legend for user provided and
built-in should be quicker now. I won't close this until we've tested it more online.

**Comment by Nightsphere** [comment]
Duplicate of Issue #125.

**Comment by smalers** [comment]
This seems to be working now.   Apparently the issue was that the default color was not handled properly in the legend.  Close this issue.
