### ISSUE TITLE
Update the version number to correct information

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#166]
The "i" icon on map legend needs to output correct information, as follows:

```
Application version:  theVersion           (get this from the application configuration file)
InfoMapper version:  theVersion          (get this from the assets version.json file)
```

I will provide direction in another issue on the copyright language.

**Comment by Nightsphere** [comment]
I have a new push out that will correctly display both version numbers now. Closing the issue.
