### ISSUE TITLE
ChartJs/StateMod time series is treating -999 as actual values

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#173]
The StateMod file format has traditionally used `-999` for missing data, even though the code can now handle `NaN`.  The Java code handled this OK so that `-999` is treated as missing in graphs, such as TSTool.  This needs to be fixed.  See example below.

![image](https://user-images.githubusercontent.com/6448274/85175742-5bb7bb80-b235-11ea-9b7c-5d97a5f19857.png)

**Comment by Nightsphere** [comment]
A new push will be up shortly that does not deal with -999 in any capacity anymore. It only assigns
NaN's throughout the data if intervals are unknown or there is a missing value. Chart.js will not connect any points that are NaN and skip them. I'll wait to close until more testing has been done.

**Comment by smalers** [comment]
The `-999` values in StateMod files indicate missing data and have been used for a long time.  The StateMod software does not know how to handle `NaN` as far as I am aware.  Therefore, I am hesitant to replace `-999` with `NaN` in all the data files.  If read in using the defaults, the code `StateMod_TS` class should be setting the values to `-999` and should also be setting the missing data value to `-999`.  Maybe what is missing is when the InfoMapper prepares the data for graphing, it needs logic like:

```
loop through time series values {
    if ( ts.isDataMissing(date) ) {
           // set value for ChartJs to NaN or null (whatever it needs)
           // Note that in the future it may still be useful to set a flag on that point,
           // if possible in the charge, for example 'M' for missing
    }
}
```

**Comment by Nightsphere** [comment]
The new push for this is up and it should be taken care from now on. Until a little more testing is done, I'll leave the issue as
open

**Comment by Nightsphere** [comment]
I believe this is taken care of. We can reopen if other graph value issues persist. Closing the issue.
