### ISSUE TITLE
Need to enable popup action to view text file

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#178]
Similar to graphs, there is a need to view a text file associated with a node.   The main difference in configuration is the `action` property will allow a value of `displayTextFile`, which will open a window to view the text file.

I'm wondering if for all of these we should somehow allow the following behavior, either through configuration or some control setting in the UI.

* popup - modal
* popup - non-modal (is this possible?)
* new tab
* new window

**Comment by smalers** [comment]
Based on a discussion with Josh, the action will be `displayText`.  The default will be to use a fixed format font (such as courier) with no wrapping and scrolling in both directions.  Resizable popup would be nice.  Attached is an example.  The second property to use would be `resourcePath`, which is the path to the resource.  If we do this, then maybe for custom CSS we could use something like `stylePath` or `cssPath`.

[example.txt](https://github.com/OpenWaterFoundation/owf-app-info-mapper-ng/files/4905815/example.txt)

**Comment by Nightsphere** [comment]
I have committed new changes so that `displayText` and `resourcePath` are new action properties, and `displayTimeSeries` is still
a default, but will become necessary probably the next push sometime early next week.

**Comment by Nightsphere** [comment]
The main showing of text files has been completed. We can open other issues if something else needs to be tended to when
it comes to displaying these text files. Closing the issue.
