### ISSUE TITLE
Change popup action from `graph` to `displayGraph`

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#179]
The action `graph` should probably be `displayGraph` to be consistent with the main  configuration file, which has `displayMap`.  This makes sense since an action is a verb.  Support the old `graph` for now also to allow some time for transition and documentation.

**Comment by smalers** [comment]
Actually, I wonder if this should be `displayTimeSeries` given that it focuses on time series product and would be similar to `displayMap`.  We can discuss when I get back from vacation.

**Comment by Nightsphere** [comment]
The new update has now changed this to use
* `displayTimeSeries` for time series graphs
* `displayText` for regular text files
* `resourcePath` for the attribute name to the files listed above e.g. `../data-ts/${featureAttribute:wdid}.txt`

I will send Steve a separate email with this information as well.
