### ISSUE TITLE
ChartJS - change how data are moved into ChartJS

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#182]
The purpose of the time series classes is to encapsulate time series data and behavior.  All other code that deals with time series should **NOT** access the time series data arrays directly.  Instead, code should first decided what period to get out of the time series:

startDateTime = a DateTime parsed from "YYYY-MM-DD" or similar
endDateTime = ...similar

If these are null, then all available data in the time series will be processed, using start and end retrieved from the time series `getDate1` and `getDate2` methods.
There are two ways to iterate through time series data:

1. Declare a `TSIterator` class (can be created using the `iterator` method on a time series).  Then use the iterator `next` method to advance the time.  This is a newer approach and must be used for irregular time series.
2. Use a for loop from start to end on `DateTime` instance and use `DateTime.addInterval`, where the interval agrees with the time series interval.  This is an older approach and only works on regular interval time series.

Once in the loop, use the `DateTime` instance for the iterator to request data from the time series using `double value = ts.getDataValue(datetime)`.  Then check for missing using `ts.isDataMissing(value)`. 

See also the `TSUtil` class `toArray` method, which is essentially what needs to be done.  This method handles many request combinations.  The Java version would benefit from a `newMissing` value to translate the time series' internal missing value to a new value, such as null or `NaN`.

**Comment by Nightsphere** [comment]
I have updated the way data are handled from the Time Series object to the configuration object used by ChartJS, and will
continue implement any other methods needed in the future. Closing this issue.
