### ISSUE TITLE
Sometimes trying to graph results in 'unknown' error

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#183]
I published the StateMod dataset viewer to the [OWF AWS S3 bucket](http://opencdss.openwaterfoundation.org/datasets/colorado/2015/#/map/cm2015-historical).  Sometimes clicking on a node and then a graph button generates an error about undefined object.  I can't tell if this is only when switching node types, for example streamflow, and then diversion or reservoir node.  It seems like something is not getting loaded quickly enough and/or asynchronous data loading issue.

![image](https://user-images.githubusercontent.com/6448274/85362396-8c208380-b4db-11ea-80c7-c8113ed7879b.png)

**Comment by smalers** [comment]
This behavior is still occurring.  I updated the S3 website with most recent version.

**Comment by Nightsphere** [comment]
This bug had to do with creating elements in the DOM for each button created that clashed with each other. It was indeed
what Steve and I were thinking at the end, so there is a check now that determines if a button HTML element has been created
yet, and removes it if it has. This way, when a user clicks on each marker on the map, a button element will be created from scratch.

I will definitely wait to close this until we're sure it's all good to go, but in the meantime, I have pushed the new fixes.

**Comment by Nightsphere** [comment]
It seems this issue has been taken care of. We can reopen this issue or open a new issue if another problem shows up. Closing
the issue.
