### ISSUE TITLE
ChartJS - set the legend for a time series to other than the main title

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#184]
The graph legend currently sets the time series legend to the same as the main title, which is going to be confusing, especially when multiple time series are shown in a graph.  The time series legend should be similar to TSTool behavior.  It may be necessary to add a new graph configuration property in TSTool to output the default legend format so that this does not need to be hard-coded in web application.  However, for now it is OK to hard-code the default format and then call code similar to TSTool.  See the [`TS.formatLegend`](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/TS/TS.java) method to format the legend string and the [`TSGraph.getLegendString`](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/GRTS/TSGraph.java) method to get the string to use in formatting.

Note that the GR and GRTS packages in Java are used for general drawing and time series drawing, respectively.  These packages are essentially replaced by a third party charting package, so have to decide how to leverage Java code.

**Comment by Nightsphere** [comment]
The ChartJS legend now displays the TSID - specifically the TSID Location - instead of the main title. Closing the issue.
