### ISSUE TITLE
Add graph configuration property to select charting package

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#185]
The ChartJS package may not meet all requirements needed for InfoMapper.  Therefore, it would be helpful to allow using alternate chart packages.  This would, for example, allow packages such as plotly to be tried and enhanced in a production environment.  The popup configuration file properties could be updated similar to the following:

```
  "actions": [
      {
        "action" : "graph",
        "chartPackage" : "ChartJS",    // or "plotly"
        "label" : "Demand",
        "productPath" : "graphs/diversion-DiversionDemand-graph-config.json"
      },
```

The `chartPackage` value should be checked case-independent.

**Comment by smalers** [comment]
Also, Sofia has made progress with plotly support and it would be good to enable that as an option so that we can compare with ChartJS.  I am particularly concerned about zooming and intelligent axes labeling, mouse-over popup showing values, and performance speed for large time series.  plotly also seems to have some nice built-in features such as export as image, etc.

**Comment by Nightsphere** [comment]
I just made a new push that starts to implement these. By default, ChartJS will still be used for now, since it's gone through
quite a bit more testing. You can however, add the `chartPackage` attribute with `plotly` to get a plotly map. As of right now,
only one time series can be displayed on a graph. I will update tomorrow for more.

**Comment by Nightsphere** [comment]
The push for this has been sent up and is now updated. The `chartPackage` attribute for each action can either not be used,
in which case plotly will be the default. It can also be set to `plotly` (case insensitive) or `chartJS` (case insensitive) to
display in whichever graphing package is preferred. Closing the issue.
