### ISSUE TITLE
Add TypeScript to read datevalue format time series

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#188]
The "DateValue" time series file format used in TSTool was created by me to fully store time series representation.  It stores time series properties and the data.  The format essentially an extended version of a CSV.  It is useful for workflows, testing, and full representation of time series.  It would be useful to support this format in web applications as an example of format that provides a lot of metadata.  The format may also be needed on some projects such as Poudre visualization.

It would be good to have this format available in the InfoMapper using "dv" file extension.  Although multiple time series can be saved, we would likely save a single time series per file.

See the [Java code](https://github.com/OpenCDSS/cdss-lib-common-java/blob/master/src/RTi/TS/DateValueTS.java).

**Comment by Nightsphere** [comment]
The core functionality has been added. DateValue files can now be read and displayed in either chartJS or plotly. Closing this issue.
