### ISSUE TITLE
Add support for raster layer

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#189]
**This issue is important because some current projects depend on this.  I have held off because we had other work to do.**

The InforMapper has focused on handling vector (geometry) layers.  It also handles background tile layers.  OWF has projects that  require displaying raster layers and therefore adding support for raster layers in the InfoMapper is needed.  Some support for raster layers is included in the GeoProcessor but more needs to be done to be able to process layers for maps similar to what has been done for vector layers.  I will need to put together an example map configuration file when I get back from vacation.  Here are some details about requirements for the InfoMapper:

1. Need basic support for GeoLayerView that is a raster rather than vector geometry.  This will use Leaflet's raster layer features.
2. One form of raster layer is an image, for example a GeoTIFF.  Such images typically have at least two of their corners geolocated so that software can "stretch" the image to fit the map projection.  Photo-type images are rendered using colors stored in the image.
3. Another form of raster is a "grid" that represents a data value for each grid cell.  For example, a digital elevation model has elevation at each grid cell.  In this case, colors must be provided to render the raster layer, similar to a color table for vector layer.  The raster might be processed into a GeoTIFF that has the colors embedded.
4. We need to understand what raster formats Leaflet supports (similar to what we have done with GeoJSON) and how to handle symbol and legend.
5. A GeoMapProject file can be mocked up to show a simple GeoTIFF and we can converge on what GeoProcessor needs to do. Then the GeoMapProject specification can be updated.
6. Raster images can be large if the grid size is small - we need to be aware of memory and performance issues.
 
I hope that the work on vector layer support can be transferred to raster layers without too much effort.

**Comment by smalers** [comment]
There will also likely need to be added functionality.  For example, the mouse-over functionality will be similar to vector layers.   Mousing over a raster cell should show the data value for the cell.  However, the default may need to be to not show mouseover popup because a raster that is an image would not have useful information.  A raster that has data would benefit from the popup.  The functionality available with Leaflet needs to be researched.

**Comment by Nightsphere** [comment]
Added raster support for the Info Mapper. If no classification file is given, the raw raster created from the tiff file will be used.
If a classification file is present, will be used to assign colors to each feature, and add them to the legend, along with the
label as the name. The mouseover/hover feature has not yet been implemented; There seems to be two functions provided
by the third party package, and from what I've researched so far, neither will be helpful. I'll keep digging around Leaflet
as well to see if I can get this working.

**Comment by Nightsphere** [comment]
Added another push for this issue that takes care of missing data. In the raster's classification file, a row beginning with an
asterisk ( * ) signifies that the data could not be matched between the classification file and the raster, so this row's attributes
will be used. Only three fields (e.g. value, fillColor, fillOpacity) in the classification file can be used for styling a cell with
missing information. If the header of the file looks like:
`value,color,opacity,fillColor,fillOpacity,weight,label`, the missing data row can be created like so:
`*,,,'#000000',0.7,,`. If the extra fields are filled out that's okay as well, the Info Mapper will just ignore them.

**Comment by Nightsphere** [comment]
I believe the core functionality has been done for this issue. Other issues can be created on a more granular level if they crop up at a later date. Closing the issue.
