### ISSUE TITLE
ChartJS dragging needs clearer visual cue

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#196]
The ChartJS graphs can be dragged but it is not obvious.   And, if you do so in the main body of the graph it jerks, as if it is trying to figure out whether dragging the graph or zooming. A better visual cue could be given to the user, for example:

1. Change the upper-right icon - it looks like a "fill screen" icon.  Maybe change to an X and enable as close?  I'm not sure there is a standard icon for "grab and drag" other than a hand, but would not want to enable that if someone wanted to see an an arrow pointer when interacting with the graph area.
2. Change the title bar area at the top to a different color, such as light grey.  People are used to using that as a handle.

**Comment by smalers** [comment]
I did look at some icons.  There are others that have hand with an arrow.  I'm not sure if this will help much.  I wonder if just making the title bar area grey will help, without needing an icon.  Chrome and other tools do this.

**Comment by Nightsphere** [comment]
Pushed new changes so that the Dialog popup is only draggable by header, and is now gray. We can test this and see if it's
the desired effect until this issue is closed.

**Comment by Nightsphere** [comment]
I believe this issue has been taken care of, not just for chartJS, but plotly, as well as any other documentation displayed in a dialog. Closing this issue.
