### ISSUE TITLE
Change Map Controls access to an icon

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#198]
The ***Map Controls***  tool is somewhat obtrusive in each layer view group, which takes away screen real estate and distracts the eye.  Users may not need to use the map controls that often given that the on/off control is easy to use.  I have the following recommendations:

1. Use a "gear" (for settings) or "wrench" (for tools) icon for map controls and place to the right of the layer view group name.  If someone clicks on the icon, it will display the map controls similar to how they are now.  Then, would need an intuitive way to close/minimize the controls.  This would free up a lot of vertical space and simplify the legend.  Maybe there is a way to leave the controls in the DOM but set to not visible and only set visible when the icon is clicked on?
2. If more icons/tools are added to the layer view group, a popup choice selector could be added, similar to the Windows tray to select USB devices, etc.
3. If functionality is needed at the top (map) level, a similar approach could be taken.
4. The layer title areas in green could get rid of some whitespace before the name, which would provide more room for icons/tools on the right.
5. We will at some point need to enable more complex visualizations on a layer or layer view group and the above would hopefully support this.
6. The information icon/tool for each layer could be shown directly to the left of the layer view on/off control.

**Comment by Nightsphere** [comment]
The gear icon has been added to the right of the geoLayerViewGroup name, and the drop down has been taken care of as
well. The information icon has also been shown to the left of the toggle layer button. It still needs to be implemented in
the geoMap and geoLayerViewGroup.

**Comment by Nightsphere** [comment]
This should be working okay now, another issue can be opened or this one reopened if something else needs to be done.
Closing the issue.
