### ISSUE TITLE
Refresh "home" URL results in an error

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#20]
I have now successfully deployed the website to the [Amazon S3 site](http://viz.openwaterfoundation.org/owf-app-poudre-dashboard/).  This immediately adds a `/home` onto the end of the URL, which makes sense because the website goes to its own home page.  However, refreshing the URL causes an error.  I suspect that loading /home directly does not initialize something?

The app needs to work with either URLs and in general needs to behave well.  I'm not sure if Justin can help with this or is Mason closer to the details.

**Comment by Nightsphere** [comment]
As of now, the 404 page has been implemented, and a home refresh is working just fine. Closing
(hopefully) for the last time.
