### ISSUE TITLE
Need better error handling for text file popup

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#200]
I implemented a text file popup.  However, I had to iterate on getting it right.  Better error handling is needed for:

1. Error in popup configuration, such as bad JSON.
2. Typo in `resourcePath`.

In some cases I saw the application error page (`There was an error loading the configuration file for this map.`) and the popup with no content.  I had to close the popup, fix the problem, and reload the map.  It would be nice to see error like: `Error loading popup configuration file: the-name-of-the-json` and `Error loading `resourcePath`:  the-value-of-resource-path`, without making the map go away.

**Comment by Nightsphere** [comment]
Error handling has been updated and is now more verbose and specific for both issues here. Closing the issue.
