### ISSUE TITLE
Sometimes blank home page is shown

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#202]
Sometimes the home page is not shown.  The page is just blank.  Refreshing the page seems to help most of the time.  The following is console output that seems to indicate the problem:

![image](https://user-images.githubusercontent.com/6448274/87453367-a07a0c80-c5bf-11ea-83af-114e11b28efe.png)

**Comment by Nightsphere** [comment]
A new push update is up, and should take care of this from now on. I'm won't close this issue until it hasn't given us any
problems for a while.

**Comment by Nightsphere** [comment]
I believe this has been fixed. We can open up the issue back up if it shows up again. Closing this issue.
