### ISSUE TITLE
Plotly graph:  enhance to handle point and line on same graph

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#214]
**This issue could be addressed in the Angular demonstration application and then code updated back to the InfoMapper.  I need Josh to coordinate with Sofia.**

I defined a graph for county population in the Poudre Basin Information application.  See the [TSTool graph configuration file](https://github.com/OpenWaterFoundation/owf-infomapper-poudre/blob/master/workflow/BasinEntities/Physical-Counties/graphs/county-population-graph-config.json).  However, the InfoMapper version does not look like the TSTool version.  See the  images below.  The following needs to be improved by handling more TSTool properties.  Attached are time series data files that correspond to the graph configuration file (I had to change the extension from `csv` to `txt` to be able to attach to this issue).

1. Handle multiple time series, in this case two year-interval time series.  This involves looping through the `data` array of the graph configuration file and adding each time series accordingly.
2. One time series has a `GraphType = Line` and the other has `GraphType = Point`.  This allows the filled data to be shown as a line and the original data to be shown as points.   We never want to misrepresent filled data as the original.  Hopefully plotly can handled this.  I found [this example](https://plotly.com/r/line-and-scatter/#plotting-markers-and-lines).
3. Add subtitle - hopefully plotly can handle this.  I found [an article](https://github.com/plotly/plotly.js/issues/233).

![image](https://user-images.githubusercontent.com/6448274/88729556-6fd2c080-d0f1-11ea-8024-13a88113a053.png)

![image](https://user-images.githubusercontent.com/6448274/88729632-9133ac80-d0f1-11ea-93d3-b3a1e5a89d6d.png)

[LARIMER.DOLA.Population.Year.filled.txt](https://github.com/OpenWaterFoundation/owf-app-info-mapper-ng/files/4991545/LARIMER.DOLA.Population.Year.filled.txt)
[LARIMER.DOLA.Population.Year.txt](https://github.com/OpenWaterFoundation/owf-app-info-mapper-ng/files/4991546/LARIMER.DOLA.Population.Year.txt)

**Comment by Nightsphere** [comment]
Multiple graphs can be shown at a time now, with differing graph types such as point and line. Subtitles can also be used with Plotly. Closing this issue.
