### ISSUE TITLE
Error displaying a map layer

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#218]
I added a layer for Trails in the Poudre application:

[http://poudre.openwaterfoundation.org/0.2.1/#/map/entities-trails](http://poudre.openwaterfoundation.org/0.2.1/#/map/entities-trails)

It took a really long time to show up on S3, which is weird, but shows up on my local machine fine.  However, when I tried to view in the above, I got the following.  I don't know if it an issue with configuration, in which case better error message may be needed, or a general issue.  I can update the application if line numbers may have changed with modified code.

Actually, I refreshed the page and the map displayed.  Maybe there is an async issue somewhere?

![image](https://user-images.githubusercontent.com/6448274/88956834-31591500-d25b-11ea-8996-e04cd986f931.png)

**Comment by Nightsphere** [comment]
I have now fixed this issue. The when another map menu button is clicked on, the leaflet popup is closed on the current map
so when the new map is created, there are no issues. Closing this issue, and issue #208.
