### ISSUE TITLE
Need to support Markdown images

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#219]
I don't know if this is simple or complex.

The use of markdown to document a layer, layer, group, or map would benefit from being able to include images in the page.  I think we are going to use an iframe or separate tab approach so the result needs to handle image location and links.  I have updated the trails documentation in the [Poudre application](https://github.com/OpenWaterFoundation/owf-infomapper-poudre/tree/master/workflow/BasinEntities/Recreation-Trails/layers/trails-fortcollins-doc) that can be used as an example:

1. Layers are stored in a `layers` folder.
2. The documentation for a layer is in ta folder `layers/trails-fortcollins-doc/`.
3. Within the folder there is a markdown file `trails-fortcollins.md` and an image that is referenced.

I used a folder in this case to experiment with how more complex documentation for a layer would be handled.  If we can get this figured out, then we have flexibility to use a single Markdown file or multiple files.

**Comment by gsofia23** [comment]
### Inline image syntax looks like this:

``` 
![Alt text](url/to/image)

![Alt text](url/to/image "Optional title")
```

- An exclamation mark: !;

- followed by a set of square brackets, containing the alt attribute text for the image;

- followed by a set of parentheses, containing the URL or path to the image, and an optional title attribute enclosed in double or single quotes.

Reference-style image syntax looks like this:
`![Alt text][id]`

The 'id' is the name of the image reference:
`[id]: url/to/image  "Optional title attribute"`


### Defining Image dimensions
To define the image dimensions , the `parseImgDimension` must be activated within app.module:
` ShowdownModule.forRoot({emoji: true, noHeaderId: true, parseImgDimensions: true, flavor: 'github'}),`

Then in the Markdown source have the image be specified as such: 
`![Alt text](url/to/image =250x250 "Optional title")`

or in reference style:
`![Alt text][id]

[id]: url/to/image =250x250`

**Comment by smalers** [comment]
I'm not sure that the additional information is supported in all tools.  Please add the URL to the reference.  Also, how does this address the core issue that we are facing?  See the link that I included in my original issue post for simple example that needs to be supported.

**Comment by Nightsphere** [comment]
The push has been made and images can now be showed. There is code so that a user just needs to specify the path relative to the markdown file being used.

For example if `waldo.png` is located in the same directory as the markdown file displaying it, the image can be displayed like so:
`![Waldo](waldo.png)`.
An absolute path can also be used:
`![Waldo](/waldo.png)`.

The code will prepend the correct path to the file name. Closing the issue.
