### ISSUE TITLE
Iframe error accessing an external website

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#221]
I am using [this markdown](https://github.com/OpenWaterFoundation/owf-infomapper-poudre/blob/master/workflow/BasinEntities/Recreation-Trails/layers/trails-fortcollins-doc/trails-fortcollins.md) to access [this website](https://www.larimer.org/naturalresources/parks/red-mountain).  However, the HTML that is displayed shows the following error when the link is used.

![image](https://user-images.githubusercontent.com/6448274/89081282-4cee1980-d348-11ea-9e2b-d2127dd27e13.png)

**Comment by Nightsphere** [comment]
iframes have been put on the back burner for now. We can reopen if we decide to try to implement them at a later date. Closing the issue.
