### ISSUE TITLE
Add viewable information for zoom level

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#222]
It can be confusing to know what zoom level the map is.  For example, it would be good to zoom into an extent that is appropriate and then use the corresponding zoom level in map configurations.  Currently, it is necessary to copy an existing configuration or find the zoom level and initial coordinates by trial and error.  I found a website that provides the zoom level:

* [NPMS Public Viewer](https://pvnpms.phmsa.dot.gov/PublicViewer/)

The zoom level is shown below the map area as follows:

![image](https://user-images.githubusercontent.com/6448274/89117023-86617a80-d457-11ea-8f49-54fa2c4c6784.png)

Something like this would be useful, but we have to be careful taking up map screen real-estate.  Maybe it can be fit in next to latitude and longitude?  Otherwise, maybe need another tool, such as activated from an icon on the left of the legend.  The zoom level is definitely helpful to people configuring maps and the scale is useful for all map users.

**Comment by Nightsphere** [comment]
The Info Mapper now shows the zoom level of the map in the lower left hand corner. The precision is by default up to 9 or 10 digits after the decimal place, so I have truncated it to just 1 digit which will play nice with the UI. Closing the issue.
