### ISSUE TITLE
Refactor Map Component code

### ISSUE THREAD

**Issue by jurentie** [OpenWaterFoundation/owf-app-info-mapper-ng#53]
Currently, all the code related to leaflet is in a single file, `map.component.ts`, and at a certain point this code is going to get very long and complicated to understand. It would be best to figure out how to put separate code in different files to make sure the code in this file doesn't get to unwieldy.

**Comment by Nightsphere** [comment]
I have created a `map.util.ts` file with the MapUtil Class to help with map creation, styling, and other miscellaneous functions that have been bloating up the map component. This will hopefully significantly reduce the amount of clutter in the `map.component.ts` file.

**Comment by Nightsphere** [comment]
The map component is much more manageable now. Further writing of code has a chance to be put into the map service or the `map.util.ts` file instead. Closing the issue.
