### ISSUE TITLE
Globals

### ISSUE THREAD

**Issue by jurentie** [OpenWaterFoundation/owf-app-info-mapper-ng#61]
Currently the global variables are found in the file `globals.ts` which is standard for Angular. The only global variable found in this file at the moment is a variable named `configurationFile` which is a path to the map tabs configuration file. However, this prevents future developers from editing this path after the project has been compiled by angular. We want to be able to allow users to customize the page using configuration files found in the assets folder, and prevent them from needing to open the angular project itself. Though seemingly redundant, it might necessary to create a configuration file that points to the map configuration file. This primary configuration file will need to remain in the same location with the same name since the project will at least need to know where this base config file is, but this allows users to move the map tabs configuration file around and also edit the name if needed.

**Comment by Nightsphere** [comment]
Global variables have been implemented throughout the application now. The only two variables
that cannot be changed are the `assets/app/` path as this was a design decision that everyone
would need to use. The second is the `app-config.json` file, which is the name of the application
configuration file and would need to be in the top-level `assets/app/` mentioned above. The path
finding has already been decided and worked on, so closing this issue.
