### ISSUE TITLE
Simplify menus to functioning tests and examples

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#72]
Now that the program has been generalized and is not serving as the Poudre Information Portal, the menus should be scaled back to those needed to demonstrate Info Mapper functionality.  I suggest using menus grouped by functionality.  If a menu becomes too large it can be broken up.  For example,  a ***Maps*** menu is obvious and the existing ***Testing*** menu can be renamed to ***Maps***.  I suggest clarifying the menu items to be consistent.  For example, ***Symbol singleSymbol Map*** is redundant.  Also, to minimize the number of maps, maybe just have one map for each geometry type and then have geoviewlayers for each symbol classification type, for example named ***Point Geometry Map*** with all 3 classification types.

There was other functionality in the work that Justin did, including Markdown content pages, maps that refresh on a schedule, etc.  Don't throw away any working code but can disable the menu in the short term until the example is working.

ASAP we need to start working on time series graphing.  I will put together a repo to help with this and then sample data can be included in the default folders.

I suggest getting the menus cleaned up in this issue and then add separate issue for each content type that needs to be fully enabled.

**Comment by Nightsphere** [comment]
Menus have been simplified for the Info Mapper. They are simple point maps, line maps, etc.

Also updated app-default so it contains more updated additions. Closing this issue.
