### ISSUE TITLE
Menu items need tool tip

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#74]
Hopefully it is easy to add tool tips to menus.  The main menus and sub-menus need a configuration element `toolTip`.  This will allow the user to mouse over a menu and get an idea what it does without having to click on it.  Need to see if tool tips display even when a menu is disabled.... which would be helpful to let users know about upcoming features.

**Comment by Nightsphere** [comment]
The tooltip property has now been added. If there is no tooltip for a menu in the `app-config.json` file,
no tooltip will display when hovered over. If it is present, then the string will be shown. This works with
all sub-menus and main menus with no sub menus, and main menus with sub-menus. Another issue
can be created later detailing any other small changes such as tooltip placement and delay. Closing
the issue.
