### ISSUE TITLE
Put GeoProcessor command files in repository

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#76]
The application is now a generic tool and therefore workflow command files used to create test data should be stored in the repository.  Because test data are generally small, it is OK to commit the data as well.  Care should be taken to not re-run and re-save test data repeatedly because it will take up space in the repository.  If necessary, a separate workflow repository can be created for test data, similar to other workflow repositories, in this case perhaps named `owf-app-info-mapper-ng-test`.

Other workflow repositories are establishing patterns for organizing GeoProcessor and other command files, but it is likely that it will vary by complexity of project.  Therefore there is no clear standard.  Here are some options and thoughts:

1) Although `assets` contains files needed by the application, command files are not needed at runtime.  Therefore, don't put command files in `assets` or even in the `info-mapper` folder.
2) We have used a `data-prep` folder in the past.  Such a folder could be created at the root level of the repository.  In there, create folders and files as necessary.
3) I recommend having a table in the main `README.md` or a separate `data-prep/README.md` that has a table listing the menu in the application, and corresponding `data-prep` location, such as a subfolder.  As the number of test examples increases, don't want all the command files and input data in one folder because it will become a mess.

**Comment by Nightsphere** [comment]
data-prep/ has been created, as has the README in it describing what data-prep/ is and the table
showing the different menus in the info-mapper. This will be updated as more menus and command files are added/removed. Closing the issue.
