### ISSUE TITLE
Need to enable basic mouseover popup functionality

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#79]
Need to implement basic functionality to mouse over a feature and seeing its attribute data.  See the following for an example:

[Municipalities](http://stories.openwaterfoundation.org/co/swsi-story-sp-entities/#munic)

Some online mapping tools require you to click on a feature to see its data but this is time-consuming.  Mousing over is much more efficient.  The general approach we have taken is:

1) Mouse over to see a popup of some data.
2) Click on a feature to see a popup with more data (or show somewhere else in the UI) and possibly provide other actions such as links to graphs etc.  The above map also implements this functionality.

The following repository has the code for popups:

[swsi-story-sp-entities](https://github.com/OpenWaterFoundation/swsi-story-sp-entities)

Some things to keep in mind:

1. There should always be some default behavior for popups, for example list all the attributes.
2. There should be an ability to customize the popup, such as with a template.  Ideally this can leverage Angular template features.
3. It can be tricky to properly display attributes.  For example, for numbers, want to control the number of digits after the decimal and possibly show with commas to indicate thousands.  These features sometimes are the most difficult to deal with.

**Comment by Nightsphere** [comment]
This basic functionality has been finished. There are more granular issues such as #111 and #207 for different behavior for a mousing over a feature. Other issues can be opened in the future if need be. Closing this issue.
