### ISSUE TITLE
Make menus behave like other applications on mouse over

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#86]
I did not notice this before, but the menus don't behave like normal menus.  The user is forced to click on each menu to see the submenus.  And once a menu is opened you have to click somewhere to close it.  I don't like doing this because the extra click I make may cause something else to happen.   Having to click is inefficient.

Having said that, I looked at other applications and menus are not what they used to be.  Microsoft apps have a "ribbon" rather than menus.  Chrome has apparently moved all menus into tool icons and menu at the right.  I suspect this comes down to researching UI component, perhaps on PrimeNG and it may be disruptive, so I am making a lower priority.  In the end we just want the user experience to be streamlined and intuitive.  Extra clicks are always problematic.

**Comment by Nightsphere** [comment]
As of right now, I think the hoverable menu drop down has been implemented in a way that's easier
than the clicking from before. Mouse over on a drop down menu will automatically show the sub
menus, and moving the mouse out of them will cause the sub menus to disappear.

The main foundation for the menus has been completed. If other smaller updates need to be
updated or changed later, other issues can be opened. Closing this issue.
