### ISSUE TITLE
Handle "generic-pages" like map data and possible need a larger assets reorganization

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#87]
The `assets/generic-pages` files need to be treated like `data-maps` because the content is specific to an application.  I had to change the content pages under `info-mapper/src/assets` rather than in my files but that is a hack.  I recommend the following:

* I think the choice of "generic-pages" was bad and we should change.
* Change the config `action` from `genericPage` to `contentPage`.
* Rename `assets/generic-pages` folder to `assets/content-pages-default` and allow for `assets/content-pages` folder.  I will then add a symbolic link in what I am doing.  I think it is safe that if the `app-config-default.json` is loaded, then using `default` in folder names is OK.  If `app-config.json` is loaded, then no `default` in folders.
* The URL also apparently uses "generic" so I'd change that consistent with the above.

I see other folders under assets.  How many more should implement defaults and allow implementations to override?  I could see how `style` might need to be replaced, or added to and probably `img`.  I don't know what `events` are.  I'm assuming that `leaflet` is but I assume that is just software that would not change.  **Maybe we should introduce a top-level assets folder and put everything under that, like**:

```
assets/
   app/
       app-config.json
       data-maps/
       data-ts/
       events/
       content-pages/
       img/
       style/
   app-default/
       app-config.json
       data-maps/
       data-ts/
       events/
       content-pages/
       img/
       style/
   leaflet/
   version.json
```

This would allow for growth.   We need to clarify when something overrides completely, such as `data-maps`, and when something adds to, for example `app/style` could incrementally add to `app-default/style`.

**Comment by Nightsphere** [comment]
I have made a new push for this. If there's any issues or something doesn't work, let me know.

**Comment by smalers** [comment]
The folders look OK.  However, the application does not display any menus.  It must be smart enough to show the `assets/app-default/content-page/home.md` but otherwise there are no menus.  I modified the `assets/.gitignore` to reflect changes to folders and removed the `.gitkeep` file since not necessary.  I pushed those changes.

**It appears that the `assets/app-default/app-config.json` file was removed from the repo somehow.**  I'm not sure how the application even worked for Josh given that this file is required and it is not in `.gitignore`.  Maybe he accidentally did not add to the staging area when committing?

I copied the old `assets/app-config-default.json` to `assets/app-default/app-config.json` and the menus showed.  I think Josh just needs to commit that file.  I'm not going to commit because he may have made other changes to that file.

**Comment by smalers** [comment]
OK, I tried to use the the latest Info Mapper with Poudre Information Portal app-config.  It seems to be picking up the menus OK, but the content pages are not found.  It seems to display the home page from the default.  I tried putting `content-pages/about-the-project` in the app config but get a 404 regardless.   I need information for how to configure to use my content pages.  I similarly need an example of how to handle the folders to find maps.  So, I'm stuck without seeing a current app config file example.

**Comment by Nightsphere** [comment]
For some reason the assets/app-default/app-config.json file was untracked, which shouldn't have mattered since I used git add -A. I'll just double check from now on what is committed. I have pushed the app-config file now

**Comment by smalers** [comment]
I think I know what happened.  The `app-config.json` file was in the `.gitignore` file from our previous file organization.  Josh did not update the `.gitignore` so it impacted his file.  I changed the `.gitignore`  which he hopefully saw recently.  There should be no mystery here and hopefully all is good.  I'm going to see if I can get some content pages and maps working using Josh's configuration file as an example.

**Comment by smalers** [comment]
Still seem to have issues.  I have the `home.md` and `about-the-project.md` files in `assets/app/content-pages/` folder but the application is displaying the files from the `app-default` folder.  If I rename the `app-default/content-pages` files to something different I get 404 errors.  The application is definitely trying to use default files and not `app` folder files.  The menus are my menus so it looks like at least some of the non-default config is being recognized.  I suggest that Josh clone out Poudre project as explained in the [Quick Start](https://github.com/OpenWaterFoundation/owf-app-poudre-dashboard-workflow#quick-start) so he can see the same behavior and fix the InfoMapper.

**Comment by smalers** [comment]
OK, I defined my own map.  The console messages indicate that even though a custom configuration is recognized, it is trying to read map files from the default location.  See the attached image.  We need to get the data folders and filenames sorted out ASAP and document.  It is too random right now.   The locations of files can't be hard-coded because over time we will need different folder structures.  Maybe need to use a variable to indicate locations, such as:

${Assets}/path-to-layer.geojson
${Assets}/path-to-map
${Assets}/path-to-classification

The above may not be needed but need to be clear as to what "." means, "../", "/", etc.  For example, I could see "." being the folder of the application configuration file.

![image](https://user-images.githubusercontent.com/6448274/81510902-9c392680-92d2-11ea-9730-e0be84eb8661.png)

**Comment by Nightsphere** [comment]
I believe this has been implemented in the Info Mapper now. Content pages have been reworked, and the assets folder has been the using the new setup for quite some time now. Closing the issue.
