### ISSUE TITLE
Content pages need to scroll

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#88]
The `generic-pages` (see other issue recommending change to `content-pages`) need to scroll if content cannot fit on the visible page.   It appears that the software tries to compress horizontally in a smart way but it does not automatically add a vertical scrollbar and therefore content is cut off.

**Comment by Nightsphere** [comment]
Now named content-pages, they are scrollable if too large to fit on the screen. Closing the issue
