### ISSUE TITLE
Would be nice to have menu separator

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#90]
Some of the lists of submenus are getting long.  It would be nice to have a menu separator as a horizontal line, similar to other software.  This could be handled as a separate menu item with a property, or add something like `separatorBefore=true` to a menu item.

**Comment by smalers** [comment]
This appears to already be implemented by default for external link.  I recommend removing the automatic separators and let developers control where they show up by using configuration information such as the above.

**Comment by Nightsphere** [comment]
A menu separator option has been added, so that each sub-menu can add `separatorBefore=true` or
`separatorBefore="true"` and a divider will be placed above it. Default is now to have no separators
anywhere unless given.

**Comment by smalers** [comment]
This looks good.  I'm closing the issue.
