### ISSUE TITLE
Content page filenames should always require extension

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#91]
Content pages in the application config file, such as markdown should always require a file extension.  This ensures that filename references match actual files without confusion.  Extensions may also be used in the future to indicate content type, rather than requiring different properties.  For example, a content page might have extension .md or .html. 

Similarly, any references to images need the file extension.

**Comment by Nightsphere** [comment]
All files in the now have file extensions, and will be added with them in the future for all
configuration files. Closing the issue
