### ISSUE TITLE
Data prep command files needed comments

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#95]
The `data-prep` command files need comments to explain what is being done.  I recommend at least documenting the purpose and content of the map and add comments for groups of commands (e.g., "Create GeoLayerViewGroup for base maps").

Otherwise, it is going to be difficult for other developers to understand the command files.

**Comment by Nightsphere** [comment]
Comments have been added to the files, and will be added to any new command files that are created.
Closing the issue.
