### ISSUE TITLE
Menu spacing seems too much

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#96]
The menu spacing seems to large.  See the image below.  It does not look like the spacing in other software.  This will also be an issue when there are many menus.

![image](https://user-images.githubusercontent.com/6448274/81491233-42404e80-9249-11ea-80d7-c0d1edd73d45.png)

**Comment by Nightsphere** [comment]
Menu spacing has been shrunken down and should be easier/less of a burden on space. Closing the issue
