### ISSUE TITLE
Config file name of map project file should include extension

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#97]
The `app-config.json` file `mapProject` values should include the `.json` for map configuration files.  It is ambiguous and confusing when file extensions are omitted.  I made a similar comment about content pages Markdown files.

**Comment by Nightsphere** [comment]
All map configuration files now have a relative path, along with the extension of the file. All new
config files will also have this as well. Closing the issue.
