### ISSUE TITLE
GeoMapProject extent used by InfoMapper does not follow specification

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-info-mapper-ng#98]
The extent properties do not seem to follow the GeoMapProject specification.  For example, the polygon geometry example map has:

```
center:'[40, -105.385]',extentInitial:8,extentMinimum:7,extentMaximum:15
```

This does not match the [Extent specification](http://software.openwaterfoundation.org/geoprocessor/latest/doc-user/appendix-geomapproject/geomapproject/#extent).  It appears that the easiest thing would be to enable the `ZoomLevel` encoding format.  Note that the GeoProcessor uses x, y, z for coordinates, which means longitude and then latititude. 

This needs to get cleaned up because it is going to impact most map configurations.

**Comment by Nightsphere** [comment]
zoomLevel has now been updated for all map configuration files. Given the Geoprocessor output of long and lat, all that needs to be set for the geoMap properties is:
`zoomLevel: '-105.385, 40, 8'`
or the desired long, lat, and zoom level. Center and all extents will not work and are deprecated.
